// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "E-Commerce",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }





import { ReactNode } from 'react';
import './globals.css'; // Import global styles
import { Josefin_Sans, Lato } from 'next/font/google'; // Importing fonts

// You can import your custom fonts like this:
const josefin = Josefin_Sans({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

const lato = Lato({
  weight: ['400'],
  subsets: ['latin'],
});

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <title>Hekto E-Commerce</title>
      </head>
      <body className={`${josefin.className} ${lato.className}`}>
        {/* Header */}
        <header>
          {/* Your header component */}
        </header>

        {/* Main Content */}
        <main>{children}</main>

        {/* Footer */}
        <footer>
          {/* Your footer component */}
        </footer>
      </body>
    </html>
  );
}
